# Generated by Django 4.1.4 on 2023-03-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_user_location_user_website_alter_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_image',
            field=models.ImageField(default='network/static/network/images/owl-silhouette.png', upload_to=''),
        ),
    ]
