# Generated by Django 4.1.4 on 2023-03-10 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='avatar',
        ),
    ]
