# Generated by Django 4.1.4 on 2023-03-03 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_user_dob_alter_user_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='message',
            new_name='new_comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post_comment',
            new_name='original_post',
        ),
    ]
