# Generated by Django 4.1.4 on 2023-03-05 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_rename_message_comment_new_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=280),
        ),
    ]
