# Generated by Django 4.1.4 on 2023-03-07 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
