# Generated by Django 4.1.4 on 2023-03-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_alter_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_image',
            field=models.ImageField(default='network/static/network/images/owl-silhouette.png', upload_to='static/network/avatars'),
        ),
    ]
