# Generated by Django 4.1.4 on 2023-03-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_alter_user_avatar_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
