# Generated by Django 4.1.4 on 2023-03-10 18:04

from django.db import migrations, models
import network.models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0019_delete_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_image',
            field=models.ImageField(default='images/owl-silhouette.png', upload_to=network.models.avatar_upload),
        ),
    ]
